DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS tasks;

CREATE TABLE users (
	id INTEGER PRIMARY KEY AUTOINCREMENT, 
	name TEXT NOT NULL,
	password TEXT NOT NULL,
    email TEXT NOT NULL
);

CREATE TABLE tasks (
	id INTEGER PRIMARY KEY AUTOINCREMENT, 
	name TEXT NOT NULL,
    task TEXT NOT NULL,
	tag TEXT NOT NULL
);


CREATE TABLE completed (
	id INTEGER PRIMARY KEY AUTOINCREMENT, 
	name TEXT NOT NULL,
    task TEXT NOT NULL,
	tag TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);